language: java
script:
  - ./gradlew assemble
  - ./gradlew check

notifications:
  email:
    recipients:
      - sangnd@vnext.vn
    on_success: always # default: change
    on_failure: always # default: always
  slack: ci-travis:DVmoGFW8BCN3iMzKZxw48wE9
